services:
  stock-bot:
    image: stock-bot:0.0.1  # 构建后镜像的名称和标签
    # 使用 scripts/docker-pre-build.sh 预构建镜像
    # build:
    #   context: .
    #   dockerfile: dockerfiles/Dockerfile
    #   args:
    #     - UV_IMAGETAG=0.8.15
    #     - NODE_IMAGETAG=24
    #     - MIRRORS_URL=${MIRRORS_URL:-"https://mirrors.ustc.edu.cn/"}
    #     - CLEAN_APT_CACHE=${CLEAN_APT_CACHE:-1}
    
    restart: unless-stopped # 重启策略
    # networks:
    #   - default
    environment:
      # -- mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_secret_password}
      MYSQL_DATABASE: stock_bot
    volumes:
      - "~/.ssh:/root/.ssh:ro" # 挂载宿主机的ssh配置文件，方便推拉代码（只读）
      - "/etc/localtime:/etc/localtime:ro" # 挂载宿主机时间到容器
      - .:/root/stock-bot
    ports:
      - 47297:2290 # 映射端口
    working_dir: /root/stock-bot
    # sleep infinity 用于保持容器运行，否则 vscode 无法进入容器，建议写在 .devcontainer/docker-compose.yml 文件中
    command: ["sleep", 'infinity']


# networks:
#   default:
#     name: stock-bot
  